module.exports = {

    KEYWORD: "KEYWORD",
    IDENTIFIER: "IDENTIFIER",

    INTEGER: "INTEGER",
    FLOAT: "FLOAT",
    STRING: "STRING",
    CHAR: "CHAR",
    BOOLEAN: "BOOLEAN",

    OPERATOR: "OPERATOR",

    LPAREN: "LPAREN",
    RPAREN: "RPAREN",

    LBRACE: "LBRACE",
    RBRACE: "RBRACE",

    LBRACKET: "LBRACKET",
    RBRACKET: "RBRACKET",

    SEMICOLON: "SEMICOLON",
    COMMA: "COMMA",

    DOT: "DOT",
    COLON: "COLON",

    EOF: "EOF"

};